### ISSUE TITLE
Find out how to handle duplicate classifications with the same direct message

### ISSUE THREAD

**Issue by bbrockman** [sscpac/chat-locker#27]
Do we remove direct messages?

**Comment by bbrockman** [comment]
Just wanted to clarify this task as I forgot the details when I originally re read it.

Brent starts a conversation with Dan and sets the classification level to something higher than unclassified.
Brent wants to start another conversation with Dan at the unclassified level.

This is not possibly because you can only have 1 direct conversation with someone.

**Comment by rwakida** [comment]
I just realized that on the backend, RocketChat sets the DM _id to user1user2 (instead of a random value) and uses 'upsert' instead of 'insert'.  I assume the logic is that there should only be one DM conversation between 2 user.  They use upsert as a shortcut to finding the existing DM room.  i.e. when clicking on a user name, they call createDirectMessage which returns the _id of newly created room or existing room (thanks to upsert).  

I think we need to modify their code to NOT use user1user2 as the _id, change upsert to insert.

**Comment by berkich** [comment]
My understanding is that the current session should be dropped and another one started. This would mean that Reid's comment above would have to be considered

**Comment by bbrockman** [comment]
Ehhh...So we'll have to ask them if they want to delete their existing conversation?  Doesn't make sense.

**Comment by rwakida** [comment]
What's the plan for this issue?

**Comment by douglasrapp** [comment]
I'm really concerned about how we can actually implement this without making it confusing/cluttered for the user. In the case of multiple DMs with the same person, would it make sense to create little submenu entries? So it might look like this:

Direct Messages
@Joe
@Bobby
@Sally
    - 1
    - 2
    - 3
@Tom

Or do you think that would even help?

**Comment by douglasrapp** [comment]
Another option could be to treat direct messages like we do public channels, and leave it only to private groups to have the option of security labels. Not a great option, but maybe something to think about.

**Comment by bbrockman** [comment]
I think this would be the best idea. We can ask the users next Monday.

**Comment by bbrockman** [comment]
Need to create multiple conversations with the same user and allow adding new classification.
