### ISSUE TITLE
Integrate Labeling / Relabeling

### ISSUE THREAD

**Issue by bbrockman** [sscpac/chat-locker#3]

**Comment by rwakida** [comment]
Should we move this from a modal window to the "flex tab" on the right?  When the direct message/private group is created, we force the flex tab to appear and show the security label configuration options.  If they close the flex tab, then the conversation is set to the default system classification and country code.  

A difference between our old impl and the new one is that we ask for the security labels BEFORE we create a direct message or private group.  With Rocket.Chat, we'll create the direct message or private group first with the default system classification and country code.  Then we'll prompt them to relabel it (but not force them to) when the conversation is displayed.  

I think this is a better route because:
1. The UI is better aligned with Rocket.Chat.  The only modal window is at registration which we are removing anyway 
2. The user will realize that the flex tab exists
3. The user will realize that they can set the security label (if needed) using the flex tab.  Clicking on the banner is not intuitive.

**Comment by berkich** [comment]
Doug and I were talking about the UI today just as you observed. I agree

**Comment by rwakida** [comment]
great ;)

**Comment by douglasrapp** [comment]
Oops, accidentally clicked a button there ;)

**Comment by douglasrapp** [comment]
Ported over the "getAllowedConversationPermissions" method from the old app for determining what perms are available.

Also modified the "directMessagesFlex" template so that when creating a new DM, upon selecting a target user (using the autocomplete select functionality), that method gets called, determines the available and required perms, returns them to the client, and prints them out in the console. Next is to do something with that data - put it in some sort of form for selecting.

**Comment by rwakida** [comment]
I noticed the branches are modifying the create Channel Flex UI instead of the direct message and private group flex UI.  The Channels are public and shouldn't be restricted right?

**Comment by douglasrapp** [comment]
Yes, that's correct. We incorrectly started implementing it on channels. Fortunately, it will just be a template that can be included from the dm/group ones.

**Comment by bbrockman** [comment]
For now yes.

**Comment by douglasrapp** [comment]
I pushed branch chat-locker-3.1 that was intended for experimenting with the "meteor-autocomplete" package currently used by Rocket Chat. Tried to use this package for selecting security labels on the front-end.

It works well enough, and has the advantage of matching Rocket's look-and-feel. However, unless a token is used on the input (e.g., the user starts typing with a '#' or '@' symbol), it will not present the user with all relevant results - rather, it waits for the user to start typing something that it can match on. We decided that this behavior did not match our use-case, and the use of a token probably isn't intuitive for the user.

For now, will continue to work with the UI elements based on the 'chosen' package that we pulled from the old version of our app - main branch chat-locker-3. But will leave branch chat-locker-3.1 intact in case we decide to re-examine.
