### ISSUE TITLE
Integrate banner into chat-locker

### ISSUE THREAD

**Issue by bbrockman** [sscpac/chat-locker#6]

**Comment by douglasrapp** [comment]
I have created branch feature/chat-locker-6 for this issue.

**Comment by douglasrapp** [comment]
The code is pretty much done. I modified the "room" template to display the security banner on top of the message area. It utilizes server-side Meteor method "getSecurityBanner" to obtain text and classification information from a list of security ids.

Since labeling has not been implemented yet, it will default to an empty list, which will result in UNCLASS / NOFORN. It will, however, try to find the labels in an "accessPermissions" field of the room document - so if you manually edit Mongo to have that field with a list of valid Id numbers, you will be able to see the banner data change.

Rather than just stop at dummy data, I went ahead and fully implemented the "getSecurityBanner" method for translating a list of ids to actual banner data. However, in order to do that, I needed to add the "AccessPermissions" class, which will be needed when we integrate the labeling/relabeling stuff.

**Comment by douglasrapp** [comment]
There's one main piece of this issue that I am not happy with - the CSS for the security banner. I was having trouble with the banner pushing down the message area such that part of it was hidden under the footer (so some messages were hidden). The only way that I was able to "fix" this in the end was to specify the height of the message area to be 100% _minus_ the height of the security banner (26px). However, that means that I hard-coded a height of 26px into the CSS, which I don't like - if we ever change the font or something of the banner, the layout will break.

Can anyone more familiar with CSS look at this for me?

**Comment by rwakida** [comment]
Looks good to me.  I modified the access permissions on the server and they were reactively reflected in the banner.

**Comment by douglasrapp** [comment]
I pulled in styling changes that Reid committed to branch 6.1, added some variables for the classification colors, and then went ahead and merged into master. Marking this done.
